#! /bin/sh
read -r -p "Для того, чтобы переустановить AssetUPnP - нажмите "ENTER" сразу, если нет (его переустанавливать не обязательно, это только в случае, когда нужно сбросить лицензию для проигрывания DSD) нажмите сначала "N" и только потом "ENTER" " response
response=${response,,} # tolower
if [[ $response =~ ^(yes|y| ) ]] | [ -z $response ]; then
echo -e "\e[31mУстанавливаем AssetUPnP\e[0m"
killall AssetUPnP
rm -R /tmp/Asset*
rm -R /usr/bin/asset/
rm -R /root/.dBpoweramp/
rm -R /.dBpoweramp
rm -r /root/Ass*
cd /usr/bin
sudo mkdir asset
sudo chmod 777 asset
cd /root
wget http://www.dbpoweramp.com/install/AssetUPnP-Linux-x64.tar.gz 
tar -zxvf AssetUPnP-Linux-x64.tar.gz  
cp -pfR  /root/Asset-R6-Linux-x64-trial/bin/ /usr/bin/asset/
chmod -R 777 /usr/bin/asset/
rm -r /root/Ass*
rm *.gz
clear
echo -e "\e[31mПожалуйста, подождите 30 секунд, и что бы не было написано на экране, нажмите кнопку выключения на сервере и после этого включите!\e[0m"
sleep 15
date +%Y%m%d -s "22000612" 
/usr/bin/asset/bin/AssetUPnP
sleep 15
reboot
fi
   exit 1;

    exit 1;
    
