#! /bin/sh
read -r -p "Для того, чтобы УДАЛИТЬ AssetUPnP - нажмите "ENTER", если нет - нажмите сначала "N"/"n" (либо другой символ) и только потом ENTER " response
response=${response,,} # tolower
if [[ $response =~ ^(yes|y| ) ]] | [ -z $response ]; then
echo -e "\e[31mУдаляем AssetUPnP\e[0m"
killall AssetUPnP
rm -R /tmp/Asset*
rm -R /usr/bin/asset/
rm -R /root/.dBpoweramp/
rm -R /.dBpoweramp
rm -r /root/Ass*
exit 1
fi
exit 1
