#! /bin/sh
umount /dev/sda2 -l
umount /dev/sda3 -l
umount /dev/sda4 -l
umount /dev/sdb1 -l
umount /dev/sdb2 -l
umount /dev/sdb3 -l
umount /dev/sdb4 -l
umount /dev/sdc1 -l
umount /dev/sdc2 -l
umount /dev/sdc3 -l
umount /dev/sdc4 -l
umount /dev/sdd1 -l
umount /dev/sdd2 -l
umount /dev/sdd3 -l
umount /dev/sdd4 -l 
e2fsck -y -f /dev/sda2 -l
e2fsck -y -f /dev/sda3 -l
e2fsck -y -f /dev/sda4 -l
e2fsck -y -f /dev/sdb1 -l
e2fsck -y -f /dev/sdb2 -l
e2fsck -y -f /dev/sdb3 -l
e2fsck -y -f /dev/sdb4 -l
e2fsck -y -f /dev/sdc1 -l
e2fsck -y -f /dev/sdc2 -l
e2fsck -y -f /dev/sdc3 -l
e2fsck -y -f /dev/sdc4 -l
e2fsck -y -f /dev/sdd1 -l
e2fsck -y -f /dev/sdd2 -l
e2fsck -y -f /dev/sdd3 -l
e2fsck -y -f /dev/sdd4 -l 
echo "проверка выполнена!! перезагрузка системы!"
reboot
