#! /bin/sh
sudo cp -pfR /update/tmpi/etc/ /
sudo cp -pfR /update/tmpi/update /root
sudo cp -pfR /update/tmpi/hdd_test /root
sed -i '/[On]MV_MONIT_SERVICE_FILESYSTEM/d' /etc/default/openmediavault
echo "OMV_MONIT_SERVICE_FILESYSTEM_SPACEUSAGE=97" >> /etc/default/openmediavault
omv-mkconf collectd
monit restart collectd
miver="$(ls /opt/minimserver/ | grep minimserver)" 
newver="minimserver-0.8.5.2"
if [ "$miver" != "$b" ];
then
ls /opt/minimserver/ | grep minimserver
wget http://jminim.com/brac/MinimServer-0.8.5.2-linux-intel.tar.gz
/opt/minimserver/bin/update MinimServer-0.8.5.2-linux-intel.tar.gz
fi
chmod 644 /etc/crontab
ver="$(uname -r)"          # get kernel release version, e.g., "3.10.34-1-MANJARO"
ver="${ver%.*-*}"        # remove suffix starting with '.' and containing '-'
ver="${ver%.*-*}"        # remove suffix starting with '.' and containing '-'
ver="${ver//.}"          # remove periods (a single `/` would do here)
echo "$ver"
b="414"
echo "$b"
if [ "$ver" != "$b" ];
then
cd /update/tmpi/
echo "downloading new kernel...."
wget http://digitall.in.ua/linux-headers.deb 
wget http://digitall.in.ua/linux-image.deb
echo "update kernel, please wait....." 
dpkg -i *.deb
read -r -p "Ядро обновлено, перегрузить? (Жмите Enter)" response
 response=${response,,} # tolower
 if [[ $response =~ ^(yes|y| ) ]] | [ -z $response ]; then
 sudo rm -R /update/tmpi && reboot
 fi
    exit 0;
 fi
 sudo bash ./AssetUPnP
 sudo rm -R /update/tmpi
    echo " у Вас последнее ядро, обновления не требуются!"   
    sleep 3
    reboot
    exit 0;
       exit 0;
