#! /bin/sh
sudo cp -pfR /update/tmpi/etc/ /
sudo cp -pfR /update/tmpi/update /root
sudo cp -pfR /update/tmpi/hdd_test /root
sed -i '/[On]MV_MONIT_SERVICE_FILESYSTEM/d' /etc/default/openmediavault
echo "OMV_MONIT_SERVICE_FILESYSTEM_SPACEUSAGE=97" >> /etc/default/openmediavault

chmod 644 /etc/crontab
ver="$(uname -r)"          # get kernel release version, e.g., "3.10.34-1-MANJARO"
ver="${ver%.*-*}"        # remove suffix starting with '.' and containing '-'
ver="${ver%.*-*}"        # remove suffix starting with '.' and containing '-'
ver="${ver//.}"          # remove periods (a single `/` would do here)
echo "$ver"
b="414"
echo "$b"
if [ "$ver" != "$b" ];
then
cd /update/tmpi/
echo "downloading new kernel...."
wget http://digitall.in.ua/linux-headers.deb 
wget http://digitall.in.ua/linux-image.deb
echo "update kernel, please wait....." 
dpkg -i *.deb
read -r -p "Ядро обновлено, перегрузить? (Жмите Enter)" response
 response=${response,,} # tolower
 if [[ $response =~ ^(yes|y| ) ]] | [ -z $response ]; then
 sudo rm -R /update/tmpi && reboot
 fi
    exit 1;
 fi
 sudo bash ./AssetUPnP
 sudo rm -R /update/tmpi
    echo " у Вас последнее ядро, обновления не требуются!"   
    sleep 3
    reboot
    exit 1;
 
