#! /bin/sh
apt-get -y --force-yes install git 
mkdir -p /update/tmpi
git clone https://github.com/norrest/omv_minimserver.git /update/tmpi/
chmod -R 777 /update/tmpi/
cd /update/tmpi/
sudo bash ./updatescript
echo "ALL DONE!"
exit 1;
