#! /bin/sh
apt-get -y install git-core 
mkdir -p /update/tmpi
git clone https://github.com/norrest/omv_minimserver.git /update/tmpi/
chmod -R 777 /update/tmpi/
cd /update/tmpi/
sudo bash ./updatescript
echo "всё выполнено!"
exit 1;

